// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Map/GenerateWorld","status":true,"description":"ワールド自動生成 Ver0.5.8(2024/6/12)","parameters":{"RetentionSaveData":"true","SeedVariable":"0","TileRegion":"1","Tilesets":"[\"{\\\"tile_set_id\\\":\\\"1\\\",\\\"boat_tile_ids\\\":\\\"[\\\\\\\"2432\\\\\\\"]\\\",\\\"ship_tile_ids\\\":\\\"[\\\\\\\"2048\\\\\\\"]\\\",\\\"airship_tile_ids\\\":\\\"[\\\\\\\"2624\\\\\\\", \\\\\\\"2720\\\\\\\"]\\\"}\"]","Maps":"","Vehicle":"true","BoatSwitch":"0","ShipSwitch":"0","AirshipSwitch":"0","Test":"","RegenerateCommand":"ワールド再生成","ExportJsonCommand":"マップJSON出力","SameMapExportJson":"false","EventExport":"false","BackupJson":"true","CommandKey":"true","RegenerateKey":"R","ExportJsonKey":"E","OutputJsonKey":"O"}}
];
