// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Map/GenerateWorld","status":true,"description":"ワールド自動生成 Ver0.5.2(2022/12/18)","parameters":{"RetentionSaveData":"true","SeedVariable":"0","TileRegion":"1","Tilesets":"[\"{\\\"tile_set_id\\\":\\\"1\\\",\\\"boat_tile_ids\\\":\\\"[\\\\\\\"2432\\\\\\\"]\\\",\\\"ship_tile_ids\\\":\\\"[\\\\\\\"2048\\\\\\\"]\\\",\\\"airship_tile_ids\\\":\\\"[\\\\\\\"2624\\\\\\\", \\\\\\\"2720\\\\\\\"]\\\"}\"]","Maps":"","RegenerateCommand":"ワールド再生成","HideRegenerateSwitch":"0","DisableRegenerateSwitch":"0","PlayTestRegenerate":"true","ExportJsonCommand":"マップJSON出力","SameMapExportJson":"false","EventExport":"false","BackupJson":"true","PlayTestExportJson":"true","CommandKey":"true","RegenerateKey":"M","ExportJsonKey":"E","OutputJsonKey":"O","PlayTestKey":"true","Vehicle":"true","BoatSwitch":"0","ShipSwitch":"0","AirshipSwitch":"0","Biome":"[\"{\\\"tile_set_id\\\":\\\"1\\\",\\\"map_id\\\":\\\"0\\\",\\\"boat_tile_ids\\\":\\\"[\\\\\\\"2432\\\\\\\"]\\\",\\\"ship_tile_ids\\\":\\\"[\\\\\\\"2048\\\\\\\"]\\\",\\\"airship_tile_ids\\\":\\\"[\\\\\\\"2624\\\\\\\", \\\\\\\"2720\\\\\\\"]\\\"}\"]"}}
];
